### ISSUE TITLE
QueryBus with null handler

### ISSUE THREAD

**Issue by iaejean** [prooph/proophessor-do-symfony#18]
I'm having problems dispatching a QueryBus, the handler is resolved as an empty string, then my process is finished but not handler

**Comment by prolic** [comment]
We probably need more info then that.

**Comment by iaejean** [comment]
My fault, I should add a tag for query bus

```yaml
prooph_service_bus:
    command_buses:
        app_domain_command_bus: ~

    query_buses:
        app_domain_query_bus: ~

    event_buses:
        app_domain_event_bus: ~

```

```yaml
  # command handlers are imported
    App\Domain\Handler\:
        resource: '../src/Domain/Handler/*Handler.php'
        public: true
        tags:
            - { name: 'prooph_service_bus.app_domain_command_bus.route_target', message_detection: true }
            - { name: 'prooph_service_bus.app_domain_query_bus.route_target', message_detection: true }
```
