### ISSUE TITLE
How to switch to async command and event routers?

### ISSUE THREAD

**Issue by ambroisemaupate** [prooph/proophessor-do-symfony#47]
There is no example to switch routers to async with Symfony configuration.

I want to implement a custom MessageProducer and a consumer based on symfony/messenger. But I don’t find any doc about wiring them into the Prooph Service-bus.

I tried to enable `async_switch` on my default command bus but the __invoke method is never called.

```yaml
# config/packages/prooph_service_bus.yaml
command_buses:
     default_command_bus:
            router:
                async_switch: 'async_message_producer'
                type: 'prooph_service_bus.command_bus_router'
```

```yaml
#services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true 
        public: false  

    async_message_producer:
        class: App\ServiceBus\Model\AsyncMessageProducer
        public: true
```

**Comment by ambroisemaupate** [comment]
Ok I figured out: all messages to be dispatched asynchronously must implement `AsyncMessage` interface. Then `AsyncMessageRouter` will route them to your AsyncMessageProducer.


```yaml
# config/packages/prooph_service_bus.yaml
prooph_service_bus:
    command_buses:
        default_command_bus:
            router:
                type: 'prooph_service_bus.command_bus_router'
    event_buses:
        default_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                async_switch: 'async_message_producer'
                type: 'prooph_service_bus.event_bus_router'
```

```yaml
# config/services.yaml
services:
    async_message_producer:
        alias: Prooph\ServiceBus\Async\MessageProducer

    Prooph\ServiceBus\Async\MessageProducer:
        class: App\ServiceBus\Model\AsyncMessageProducer

    App\ServiceBus\Model\AsyncMessageHandler:
        arguments: ['@prooph_service_bus.default_event_bus']
        tags: ['messenger.message_handler']
```

Then `composer require amqp` and configure your Symfony Messenger component:

```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "async"
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
            '*': async

    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
```

Choose which event will be dispatched to your async router just by implementing `AsyncMessage`:

```php
declare(strict_types=1);

namespace App\EventStore\Model\Payment\Event;

use Prooph\EventSourcing\AggregateChanged;
use Prooph\ServiceBus\Async\AsyncMessage;

final class PaymentWasCompleted extends AggregateChanged implements AsyncMessage
{
…
```
